# Generated by Django 5.1.3 on 2025-04-16 22:04

import django.contrib.auth.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('salon', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='barbers', to='salon.shop', verbose_name='آرایشگاه'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, related_name='%(app_label)s_%(class)s_related', related_query_name='%(app_label)s_%(class)ss', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.CreateModel(
            name='Barber',
            fields=[
            ],
            options={
                'verbose_name': 'آرایشگر',
                'verbose_name_plural': 'آرایشگران',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('account.userprofile',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
            ],
            options={
                'verbose_name': 'مشتری',
                'verbose_name_plural': 'مشتریان',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('account.userprofile',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
            ],
            options={
                'verbose_name': 'مدیر',
                'verbose_name_plural': 'مدیران',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('account.userprofile',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
