# Generated by Django 5.1.3 on 2025-04-16 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(verbose_name='زمان شروع')),
                ('end_time', models.DateTimeField(verbose_name='زمان پایان')),
                ('status', models.CharField(choices=[('pending', 'در انتظار تایید'), ('confirmed', 'تایید شده'), ('canceled', 'لغو شده')], default='pending', max_length=10, verbose_name='وضعیت نوبت')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
            ],
            options={
                'verbose_name': 'نوبت',
                'verbose_name_plural': 'نوبت\u200cها',
            },
        ),
        migrations.CreateModel(
            name='AppointmentService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='تعداد')),
            ],
            options={
                'verbose_name': 'خدمت نوبت',
                'verbose_name_plural': 'خدمات نوبت\u200cها',
            },
        ),
        migrations.CreateModel(
            name='CustomerShop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ عضویت')),
            ],
            options={
                'verbose_name': 'عضویت مشتری',
                'verbose_name_plural': 'عضویت\u200cهای مشتریان',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام خدمت')),
                ('duration', models.PositiveIntegerField(verbose_name='مدت زمان (دقیقه)')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='قیمت (تومان)')),
            ],
            options={
                'verbose_name': 'خدمت',
                'verbose_name_plural': 'خدمات',
            },
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام آرایشگاه')),
                ('referral_code', models.CharField(max_length=8, unique=True, verbose_name='کد یکتای جستجو')),
                ('address', models.TextField(verbose_name='آدرس دقیق')),
                ('phone', models.CharField(max_length=15, verbose_name='شماره تماس')),
                ('status', models.CharField(choices=[('active', 'فعال'), ('inactive', 'غیرفعال')], default='active', max_length=10, verbose_name='وضعیت')),
                ('latitude', models.FloatField(blank=True, null=True, verbose_name='عرض جغرافیایی')),
                ('longitude', models.FloatField(blank=True, null=True, verbose_name='طول جغرافیایی')),
            ],
            options={
                'verbose_name': 'آرایشگاه',
                'verbose_name_plural': 'آرایشگاه\u200cها',
            },
        ),
    ]
