# Generated by Django 5.1.3 on 2025-07-14 14:21

import django.db.models.deletion
import salon.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('status', models.CharField(choices=[('pending', 'در انتظار'), ('confirmed', 'تأیید شده'), ('canceled', 'لغو شده'), ('completed', 'تکمیل شده')], default='pending', max_length=20)),
                ('canceled_by', models.CharField(blank=True, choices=[('customer', 'مشتری'), ('manager', 'مدیر')], max_length=10, null=True, verbose_name='لغوکننده')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('barber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='barber_appointments', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('url', models.URLField(blank=True, null=True)),
                ('type', models.CharField(choices=[('appointment_confirmed', 'Appointment Confirmed'), ('appointment_canceled', 'Appointment Canceled'), ('other', 'Other')], default='other', max_length=50)),
                ('appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='salon.appointment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام خدمت')),
                ('duration', models.PositiveIntegerField(verbose_name='مدت زمان (دقیقه)')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='قیمت (تومان)')),
                ('barber', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='services', to='account.barberprofile', verbose_name='آرایشگر')),
            ],
            options={
                'verbose_name': 'خدمت',
                'verbose_name_plural': 'خدمات',
            },
        ),
        migrations.CreateModel(
            name='AppointmentService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selected_services', to='salon.appointment', verbose_name='نوبت')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salon.service', verbose_name='خدمت انتخابی')),
            ],
            options={
                'verbose_name': 'خدمت نوبت',
                'verbose_name_plural': 'خدمات نوبت\u200cها',
            },
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام آرایشگاه')),
                ('referral_code', models.CharField(max_length=8, unique=True, verbose_name='کد یکتای جستجو')),
                ('address', models.TextField(verbose_name='آدرس دقیق')),
                ('phone', models.CharField(max_length=15, verbose_name='شماره تماس')),
                ('status', models.CharField(choices=[('open', 'باز'), ('close', 'بسته'), ('active', 'فعال'), ('inactive', 'غیرفعال')], default='active', max_length=10, verbose_name='وضعیت')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('logo', models.ImageField(blank=True, null=True, upload_to=salon.models.get_random_logo_name)),
                ('image_shop', models.ImageField(blank=True, null=True, upload_to=salon.models.get_random_image_shop_name)),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='managed_shops', to=settings.AUTH_USER_MODEL, verbose_name='مدیر مسئول')),
            ],
            options={
                'verbose_name': 'آرایشگاه',
                'verbose_name_plural': 'آرایشگاه\u200cها',
            },
        ),
        migrations.AddField(
            model_name='service',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='salon.shop', verbose_name='آرایشگاه'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='salon.shop'),
        ),
        migrations.CreateModel(
            name='ShopSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.CharField(choices=[('saturday', 'شنبه'), ('sunday', 'یک\u200cشنبه'), ('monday', 'دوشنبه'), ('tuesday', 'سه\u200cشنبه'), ('wednesday', 'چهارشنبه'), ('thursday', 'پنج\u200cشنبه'), ('friday', 'جمعه')], max_length=10)),
                ('is_open', models.BooleanField(default=True)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('break_start', models.TimeField(blank=True, null=True)),
                ('break_end', models.TimeField(blank=True, null=True)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='salon.shop')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerShop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ عضویت')),
                ('is_active', models.BooleanField(default=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shop_memberships', to=settings.AUTH_USER_MODEL, verbose_name='مشتری')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_memberships', to='salon.shop', verbose_name='آرایشگاه')),
            ],
            options={
                'verbose_name': 'عضویت مشتری',
                'verbose_name_plural': 'عضویت\u200cهای مشتریان',
                'unique_together': {('customer', 'shop')},
            },
        ),
        migrations.CreateModel(
            name='BarberSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.CharField(choices=[('saturday', 'شنبه'), ('sunday', 'یک\u200cشنبه'), ('monday', 'دوشنبه'), ('tuesday', 'سه\u200cشنبه'), ('wednesday', 'چهارشنبه'), ('thursday', 'پنج\u200cشنبه'), ('friday', 'جمعه')], max_length=10)),
                ('is_open', models.BooleanField(default=True)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('break_start', models.TimeField(blank=True, null=True)),
                ('break_end', models.TimeField(blank=True, null=True)),
                ('barber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules_barber', to='account.barberprofile')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule', to='salon.shop')),
            ],
            options={
                'unique_together': {('shop', 'barber', 'day_of_week')},
            },
        ),
        migrations.AddConstraint(
            model_name='appointment',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'canceled'), _negated=True), fields=('barber', 'start_time'), name='unique_barber_start_time_active'),
        ),
        migrations.AlterUniqueTogether(
            name='shopschedule',
            unique_together={('shop', 'day_of_week')},
        ),
    ]
