# Generated by Django 5.1.3 on 2025-06-02 11:06

import salon.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='image_shop',
            field=models.ImageField(blank=True, null=True, upload_to=salon.models.get_random_image_shop_name),
        ),
        migrations.AddField(
            model_name='shop',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=salon.models.get_random_logo_name),
        ),
    ]
