# Generated by Django 5.1.3 on 2025-04-16 22:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0002_initial'),
        ('salon', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='barber',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='barber_appointments', to='account.barber', verbose_name='آرایشگر'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_appointments', to='account.customer', verbose_name='مشتری'),
        ),
        migrations.AddField(
            model_name='appointmentservice',
            name='appointment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selected_services', to='salon.appointment', verbose_name='نوبت'),
        ),
        migrations.AddField(
            model_name='customershop',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shop_memberships', to='account.customer', verbose_name='مشتری'),
        ),
        migrations.AddField(
            model_name='appointmentservice',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salon.service', verbose_name='خدمت انتخابی'),
        ),
        migrations.AddField(
            model_name='shop',
            name='manager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='managed_shops', to=settings.AUTH_USER_MODEL, verbose_name='مدیر مسئول'),
        ),
        migrations.AddField(
            model_name='service',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='salon.shop', verbose_name='آرایشگاه'),
        ),
        migrations.AddField(
            model_name='customershop',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_memberships', to='salon.shop', verbose_name='آرایشگاه'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='salon.shop', verbose_name='آرایشگاه'),
        ),
        migrations.AlterUniqueTogether(
            name='customershop',
            unique_together={('customer', 'shop')},
        ),
        migrations.AlterUniqueTogether(
            name='appointment',
            unique_together={('barber', 'start_time')},
        ),
    ]
