# Generated by Django 5.1.3 on 2025-04-25 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='service',
        ),
        migrations.RemoveField(
            model_name='appointmentservice',
            name='quantity',
        ),
    ]
