# Generated by Django 5.1.3 on 2025-05-25 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0002_remove_appointment_unique_barber_appointment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='canceled_by',
            field=models.CharField(blank=True, choices=[('customer', 'مشتری'), ('manager', 'مدیر')], max_length=10, null=True, verbose_name='لغوکننده'),
        ),
    ]
