# Generated by Django 5.1.3 on 2025-12-31 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0003_city_province_shop_city_district_shop_district_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='غعال؟'),
        ),
    ]
