# Generated by Django 5.1.3 on 2026-02-11 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0004_service_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('pending', 'بی\u200cپاسخ'), ('confirmed', 'پذیرفته\u200cشده'), ('canceled', 'لغو شده'), ('completed', 'انجام شده'), ('missed', 'انجام نشده')], default='pending', max_length=20),
        ),
    ]
