# Generated by Django 5.1.3 on 2025-10-23 09:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_initial'),
        ('salon', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barberprofile',
            name='shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='barber_shop', to='salon.shop'),
        ),
    ]
