# Generated by Django 5.1.3 on 2025-12-19 15:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_initial'),
        ('salon', '0003_city_province_shop_city_district_shop_district_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='barberprofile',
            name='status_barber',
            field=models.CharField(choices=[('invited', 'Invited'), ('active', 'Active'), ('suspended', 'Suspended'), ('left', 'Left')], default='active', max_length=20, verbose_name='وضعیت آرایشگر'),
        ),
        migrations.AlterField(
            model_name='barberprofile',
            name='shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='barber_shop', to='salon.shop'),
        ),
    ]
