# Generated by Django 5.1.3 on 2025-12-24 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_barberprofile_status_barber_alter_barberprofile_shop'),
    ]

    operations = [
        migrations.AddField(
            model_name='barberprofile',
            name='invited_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
